import sys
from PySide6.QtCore import (QCoreApplication, QRect, QSize, Qt)
from PySide6.QtGui import QIcon
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit, QMainWindow, QPushButton, QStackedWidget, QTableWidget, QTableWidgetItem, QVBoxLayout, QWidget)

class UiMainKiosko():
    def setupUi(self, MainKiosko):
        MainKiosko.setWindowTitle(QCoreApplication.translate("MainKiosko", "Gestor de Stock"))
        MainKiosko.setObjectName("MainKiosko")
        MainKiosko.setFixedSize(900, 600) # dimenciones de la ventana.
        icon = QIcon()
        icon.addFile("vista/icons/kiosko.ico", QSize(), QIcon.Normal, QIcon.Off)
        MainKiosko.setWindowIcon(icon)
        MainKiosko.setStyleSheet("background-color: rgb(36, 36, 36); font: 10pt \"Arial\";")
        MainKiosko.setIconSize(QSize(30, 30))
        self.centralwidget = QWidget(MainKiosko)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutMain = QVBoxLayout(self.centralwidget)
        self.layoutMain.setSpacing(0)
        self.layoutMain.setObjectName("layoutMain")
        self.layoutMain.setContentsMargins(0, 0, 0, 0)
        self.framePrincipal = QFrame(self.centralwidget)
        self.framePrincipal.setObjectName("framePrincipal")
        self.framePrincipal.setFrameShape(QFrame.StyledPanel)
        self.framePrincipal.setFrameShadow(QFrame.Raised)
        self.layoutDelFramePrincipal = QVBoxLayout(self.framePrincipal)
        self.layoutDelFramePrincipal.setSpacing(0)
        self.layoutDelFramePrincipal.setObjectName("layoutDelFramePrincipal")
        self.layoutDelFramePrincipal.setContentsMargins(0, 0, 0, 0)

        self.paginas = QStackedWidget(self.framePrincipal) # Contenedor de paginas.
        self.paginas.setObjectName("paginas")

        self.encabezadosTabla=["ID","PRODUCTO","MARCA","PRECIO $","STOCK","INFLACION % "] # encabezados para tablas

        self.paginaInicial = QWidget() # Pagina Inicial (Portada).
        self.paginaInicial.setObjectName("paginaInicial")
        self.paginaInicial.setStyleSheet("QPushButton:hover""{""background-color:  rgb(58, 72, 80);""}")
        self.layoutPaginaInicial = QVBoxLayout(self.paginaInicial)
        self.layoutPaginaInicial.setSpacing(0)
        self.layoutPaginaInicial.setObjectName("layoutPaginaInicial")
        self.layoutPaginaInicial.setContentsMargins(0, 0, 0, 0)
        self.botonInicial = QPushButton(self.paginaInicial)
        self.botonInicial.setObjectName("botonInicial")
        self.botonInicial.setMinimumSize(QSize(900, 600))
        icon1 = QIcon()
        icon1.addFile("vista/icons/imgInicio.png", QSize(), QIcon.Normal, QIcon.Off)
        self.botonInicial.setIcon(icon1)
        self.botonInicial.setIconSize(QSize(330, 330))
        self.layoutPaginaInicial.addWidget(self.botonInicial)
        self.paginas.addWidget(self.paginaInicial)

        self.paginaMenu = QWidget() # Pagina Menu.
        self.paginaMenu.setObjectName("paginaMenu")
        self.paginaMenu.setStyleSheet("QPushButton{background-color: rgb(54, 54, 54); border-radius: 25px;}""QPushButton:hover""{""background-color:  rgb(103, 136, 150);""}")

    # Botones del menu.    
        self.botonStock = QPushButton(self.paginaMenu)
        self.botonStock.setObjectName("botonStock")
        self.botonStock.setGeometry(QRect(90, 60, 180, 180))
        self.botonStock.setMinimumSize(QSize(180, 180))
        icon2 = QIcon()
        icon2.addFile("vista/icons/stock.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.botonStock.setIcon(icon2)
        self.botonStock.setIconSize(QSize(110, 110))
        self.botonRegistrar = QPushButton(self.paginaMenu)
        self.botonRegistrar.setObjectName("botonRegistrar")
        self.botonRegistrar.setGeometry(QRect(360, 60, 180, 180))
        self.botonRegistrar.setMinimumSize(QSize(180, 180))
        icon3 = QIcon()
        icon3.addFile("vista/icons/registrar.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.botonRegistrar.setIcon(icon3)
        self.botonRegistrar.setIconSize(QSize(110, 110))
        self.botonActualizar = QPushButton(self.paginaMenu)
        self.botonActualizar.setObjectName("botonActualizar")
        self.botonActualizar.setGeometry(QRect(630, 60, 180, 180))
        self.botonActualizar.setMinimumSize(QSize(180, 180))
        icon4 = QIcon()
        icon4.addFile("vista/icons/actualizar.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.botonActualizar.setIcon(icon4)
        self.botonActualizar.setIconSize(QSize(110, 110))
        self.botonEliminar = QPushButton(self.paginaMenu)
        self.botonEliminar.setObjectName("botonEliminar")
        self.botonEliminar.setGeometry(QRect(90, 320, 180, 180))
        self.botonEliminar.setMinimumSize(QSize(180, 180))
        icon5 = QIcon()
        icon5.addFile("vista/icons/eliminar.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.botonEliminar.setIcon(icon5)
        self.botonEliminar.setIconSize(QSize(110, 110))
        self.botonAjustes = QPushButton(self.paginaMenu)
        self.botonAjustes.setObjectName("botonAjustes")
        self.botonAjustes.setGeometry(QRect(360, 320, 180, 180))
        self.botonAjustes.setMinimumSize(QSize(180, 180))
        icon6 = QIcon()
        icon6.addFile("vista/icons/seting.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.botonAjustes.setIcon(icon6)
        self.botonAjustes.setIconSize(QSize(110, 110))
        self.botonInfo = QPushButton(self.paginaMenu)
        self.botonInfo.setObjectName("botonInfo")
        self.botonInfo.setGeometry(QRect(630, 320, 180, 180))
        self.botonInfo.setMinimumSize(QSize(180, 180))
        icon7 = QIcon()
        icon7.addFile("vista/icons/6_info.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.botonInfo.setIcon(icon7)
        self.botonInfo.setIconSize(QSize(100, 100))
        self.labelStock = QLabel(self.paginaMenu)
        self.labelStock.setObjectName("labelStock")
        self.labelStock.setGeometry(QRect(130, 240, 91, 31))
        self.labelStock.setStyleSheet("color: rgb(255, 255, 255); font: 11pt \"Arial\";")
        self.labelStock.setText(QCoreApplication.translate("paginaMenu", "Stock"))
        self.labelStock.setAlignment(Qt.AlignCenter)
        self.labelEliminar = QLabel(self.paginaMenu)
        self.labelEliminar.setObjectName("labelEliminar")
        self.labelEliminar.setGeometry(QRect(120, 500, 121, 31))
        self.labelEliminar.setStyleSheet("color: rgb(255, 255, 255); font: 11pt \"Arial\";")
        self.labelEliminar.setText(QCoreApplication.translate("paginaMenu", "Eliminar"))
        self.labelEliminar.setAlignment(Qt.AlignCenter)
        self.labelRegistrar = QLabel(self.paginaMenu)
        self.labelRegistrar.setObjectName("labelRegistrar")
        self.labelRegistrar.setGeometry(QRect(410, 240, 91, 31))
        self.labelRegistrar.setStyleSheet("color: rgb(255, 255, 255); font: 11pt \"Arial\";")
        self.labelRegistrar.setText(QCoreApplication.translate("paginaMenu", "Registrar"))
        self.labelRegistrar.setAlignment(Qt.AlignCenter)
        self.labelAjustes = QLabel(self.paginaMenu)
        self.labelAjustes.setObjectName("labelAjustes")
        self.labelAjustes.setGeometry(QRect(380, 500, 141, 31))
        self.labelAjustes.setStyleSheet("color: rgb(255, 255, 255); font: 11pt \"Arial\";")
        self.labelAjustes.setText(QCoreApplication.translate("paginaMenu", "Ajustes"))
        self.labelAjustes.setAlignment(Qt.AlignCenter)
        self.labelActualizar = QLabel(self.paginaMenu)
        self.labelActualizar.setObjectName("labelActualizar")
        self.labelActualizar.setGeometry(QRect(670, 240, 111, 21))
        self.labelActualizar.setStyleSheet("color: rgb(255, 255, 255); font: 11pt \"Arial\";")
        self.labelActualizar.setText(QCoreApplication.translate("paginaMenu", "Actualizar"))
        self.labelActualizar.setAlignment(Qt.AlignCenter)
        self.labelInfo = QLabel(self.paginaMenu)
        self.labelInfo.setObjectName("labelInfo")
        self.labelInfo.setGeometry(QRect(660, 500, 121, 31))
        self.labelInfo.setStyleSheet("color: rgb(255, 255, 255); font: 11pt \"Arial\";")
        self.labelInfo.setText(QCoreApplication.translate("paginaMenu", "Info"))
        self.labelInfo.setAlignment(Qt.AlignCenter)
        self.paginas.addWidget(self.paginaMenu)

        self.paginaStock = QWidget() # Pagina Stock.
        self.paginaStock.setObjectName("paginaStock")
        self.paginaStock.setStyleSheet("QPushButton:hover""{""background-color:  rgb(70, 70, 70);""}")
        self.inputBuscarEnStock = QLineEdit(self.paginaStock)
        self.inputBuscarEnStock.setObjectName("inputBuscarEnStock")
        self.inputBuscarEnStock.setGeometry(QRect(230, 60, 461, 41))
        self.inputBuscarEnStock.setStyleSheet("color: rgb(255, 255, 255); font: 10pt \"Consolas\"; background-color: rgb(85, 85, 85); border-radius: 18px;")
        self.inputBuscarEnStock.setPlaceholderText(QCoreApplication.translate("paginaStock", "Buscar"))
        self.inputBuscarEnStock.setAlignment(Qt.AlignCenter)
        self.botonAtrasEnStock = QPushButton(self.paginaStock)
        self.botonAtrasEnStock.setObjectName("botonAtrasEnStock")
        self.botonAtrasEnStock.setGeometry(QRect(0, 0, 41, 41))
        self.botonAtrasEnStock.setStyleSheet("QPushButton{border-radius: 5px;}""QPushButton:hover {background-color:  rgb(70, 70, 70);}")
        self.botonAtrasEnStock.setToolTip(QCoreApplication.translate("paginaStock", "Atras"))
        icon8 = QIcon()
        icon8.addFile("vista/icons/atras.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.botonAtrasEnStock.setIcon(icon8)
        self.botonAtrasEnStock.setIconSize(QSize(25, 25))

        self.tablaStock = QTableWidget(self.paginaStock) # Tabla Stock.
        self.tablaStock.setColumnCount(6)
        for encabezado, num in zip(self.encabezadosTabla,range(6)): # coloca encabezados a la tabla stock.
            tablWidgetItem0=QTableWidgetItem()
            self.tablaStock.setHorizontalHeaderItem(num, tablWidgetItem0)
            tablWidgetItem0.setText(QCoreApplication.translate("paginaStock",encabezado))

        self.tablaStock.setObjectName("tablaStock")
        self.tablaStock.setGeometry(QRect(0, 150, 901, 381))
        self.tablaStock.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.tablaStock.setAlternatingRowColors(True)
        self.tablaStock.horizontalHeader().setCascadingSectionResizes(True)
        self.tablaStock.horizontalHeader().setHighlightSections(False)
        self.tablaStock.horizontalHeader().setProperty("showSortIndicator", False)
        self.tablaStock.horizontalHeader().setStretchLastSection(True)
        self.tablaStock.verticalHeader().setVisible(False)
        self.tablaStock.verticalHeader().setMinimumSectionSize(23)
        self.tablaStock.verticalHeader().setHighlightSections(False)
        self.tablaStock.verticalHeader().setProperty("showSortIndicator", False)
        self.tablaStock.verticalHeader().setStretchLastSection(False)
        self.paginas.addWidget(self.paginaStock)

        self.paginaRegistrar = QWidget() # Pagina Registrar.
        self.paginaRegistrar.setObjectName("paginaRegistrar")
        self.paginaRegistrar.setStyleSheet("QLabel {color: rgb(255, 255, 255); font: 9pt \"Arial\";}""QLineEdit{color: rgb(255, 255, 255); font: 10pt \"Consolas\"; background-color: rgb(85, 85, 85); border-radius: 18px;}")
        self.labelTituloRegistrarProducto = QLabel(self.paginaRegistrar)
        self.labelTituloRegistrarProducto.setObjectName("labelTituloRegistrarProducto")
        self.labelTituloRegistrarProducto.setGeometry(QRect(200, 40, 521, 61))
        self.labelTituloRegistrarProducto.setStyleSheet("color: rgb(255, 255, 255);""font: 700 40pt \"Calibri\";")
        self.labelTituloRegistrarProducto.setText(QCoreApplication.translate("paginaRegistrar", "REGISTRAR PRODUCTO"))
        self.labelTituloRegistrarProducto.setAlignment(Qt.AlignCenter)
        self.labelProductoEnRegistrar = QLabel(self.paginaRegistrar)
        self.labelProductoEnRegistrar.setObjectName("labelProductoEnRegistrar")
        self.labelProductoEnRegistrar.setGeometry(QRect(230, 160, 131, 31))
        self.labelProductoEnRegistrar.setStyleSheet("font: 16pt \"Arial\";")
        self.labelProductoEnRegistrar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.labelMarcaEnRegistrar = QLabel(self.paginaRegistrar)
        self.labelMarcaEnRegistrar.setObjectName("labelMarcaEnRegistrar")
        self.labelMarcaEnRegistrar.setGeometry(QRect(260, 230, 101, 31))
        self.labelMarcaEnRegistrar.setStyleSheet("font: 16pt \"Arial\";")
        self.labelMarcaEnRegistrar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.labelPrecioEnRegistrar = QLabel(self.paginaRegistrar)
        self.labelPrecioEnRegistrar.setObjectName("labelPrecioEnRegistrar")
        self.labelPrecioEnRegistrar.setGeometry(QRect(240, 310, 121, 21))
        self.labelPrecioEnRegistrar.setStyleSheet("font: 16pt \"Arial\";")
        self.labelPrecioEnRegistrar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.labelStockEnRegistrar = QLabel(self.paginaRegistrar)
        self.labelStockEnRegistrar.setObjectName("labelStockEnRegistrar")
        self.labelStockEnRegistrar.setGeometry(QRect(280, 370, 81, 31))
        self.labelStockEnRegistrar.setStyleSheet("font: 16pt \"Arial\";")
        self.labelStockEnRegistrar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.labelInflacionEnRegistrar = QLabel(self.paginaRegistrar)
        self.labelInflacionEnRegistrar.setObjectName("labelInflacionEnRegistrar")
        self.labelInflacionEnRegistrar.setGeometry(QRect(210, 450, 151, 21))
        self.labelInflacionEnRegistrar.setStyleSheet("font: 16pt \"Arial\";")
        self.labelInflacionEnRegistrar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.inputProductoEnRegistrar = QLineEdit(self.paginaRegistrar)
        self.inputProductoEnRegistrar.setObjectName("inputProductoEnRegistrar")
        self.inputProductoEnRegistrar.setGeometry(QRect(380, 160, 311, 41))
        self.inputProductoEnRegistrar.setAlignment(Qt.AlignCenter)
        self.inputMarcaEnRegistrar = QLineEdit(self.paginaRegistrar)
        self.inputMarcaEnRegistrar.setObjectName("inputMarcaEnRegistrar")
        self.inputMarcaEnRegistrar.setGeometry(QRect(380, 230, 311, 41))
        self.inputMarcaEnRegistrar.setAlignment(Qt.AlignCenter)
        self.inputPrecioEnRegistrar = QLineEdit(self.paginaRegistrar)
        self.inputPrecioEnRegistrar.setObjectName("inputPrecioEnRegistrar")
        self.inputPrecioEnRegistrar.setGeometry(QRect(380, 300, 311, 41))
        self.inputPrecioEnRegistrar.setAlignment(Qt.AlignCenter)
        self.inputStockEnRegistrar = QLineEdit(self.paginaRegistrar)
        self.inputStockEnRegistrar.setObjectName("inputStockEnRegistrar")
        self.inputStockEnRegistrar.setGeometry(QRect(380, 370, 311, 41))
        self.inputStockEnRegistrar.setAlignment(Qt.AlignCenter)
        self.inputInflacionEnRegistrar = QLineEdit(self.paginaRegistrar)
        self.inputInflacionEnRegistrar.setObjectName("inputInflacionEnRegistrar")
        self.inputInflacionEnRegistrar.setGeometry(QRect(380, 440, 311, 41))
        self.inputInflacionEnRegistrar.setAlignment(Qt.AlignCenter)
        self.botonAtrasEnRegistrar = QPushButton(self.paginaRegistrar)
        self.botonAtrasEnRegistrar.setObjectName("botonAtrasEnRegistrar")
        self.botonAtrasEnRegistrar.setGeometry(QRect(0, 0, 41, 41))
        self.botonAtrasEnRegistrar.setStyleSheet("QPushButton{border-radius: 5px;}""QPushButton:hover {background-color:  rgb(70, 70, 70);}")
        self.botonAtrasEnRegistrar.setToolTip(QCoreApplication.translate("paginaRegistrar", "Atras"))
        self.botonAtrasEnRegistrar.setIcon(icon8)
        self.botonAtrasEnRegistrar.setIconSize(QSize(25, 25))
        self.botonRegistrarEnRegistrar = QPushButton(self.paginaRegistrar)
        self.botonRegistrarEnRegistrar.setObjectName("botonRegistrarEnRegistrar")
        self.botonRegistrarEnRegistrar.setGeometry(QRect(760, 530, 91, 31))
        self.botonRegistrarEnRegistrar.setStyleSheet("QPushButton{color: rgb(255, 255, 255); font: 10pt \"Consolas\"; background-color: rgb(100, 100, 100); border-radius: 10px;}""QPushButton:hover {background-color:  rgb(63, 133, 149);}")
        self.botonRegistrarEnRegistrar.setText(QCoreApplication.translate("paginaRegistrar", "Registrar"))
        self.labelConfirmacionDeRegistro = QLabel(self.paginaRegistrar)
        self.labelConfirmacionDeRegistro.setObjectName("labelConfirmacionDeRegistro")
        self.labelConfirmacionDeRegistro.setGeometry(QRect(40, 530, 171, 31))
        self.labelConfirmacionDeRegistro.setStyleSheet("color: rgb(151, 255, 151); font: 9pt \"Consolas\";")
    #Etiquetas.
        self.labelProductoEnRegistrar.setText(QCoreApplication.translate("paginaRegistrar", "PRODUCTO:"))
        self.labelMarcaEnRegistrar.setText(QCoreApplication.translate("paginaRegistrar", "MARCA:"))
        self.labelPrecioEnRegistrar.setText(QCoreApplication.translate("paginaRegistrar", "PRECIO $:"))
        self.labelStockEnRegistrar.setText(QCoreApplication.translate("paginaRegistrar", "STOCK:"))
        self.labelInflacionEnRegistrar.setText(QCoreApplication.translate("paginaRegistrar", "INFLACION %:"))
        self.inputProductoEnRegistrar.setPlaceholderText(QCoreApplication.translate("paginaRegistrar", "Ingrese el producto"))
        self.inputMarcaEnRegistrar.setPlaceholderText(QCoreApplication.translate("paginaRegistrar", "Ingrese la marca"))
        self.inputPrecioEnRegistrar.setPlaceholderText(QCoreApplication.translate("paginaRegistrar", "Ingrese el precio"))
        self.inputStockEnRegistrar.setPlaceholderText(QCoreApplication.translate("paginaRegistrar", "Ingrese la cantidad"))
        self.inputInflacionEnRegistrar.setPlaceholderText(QCoreApplication.translate("paginaRegistrar", "Ingrese el porcentaje"))
        self.paginas.addWidget(self.paginaRegistrar)

        self.paginaActualizar = QWidget() # Pagina actualizar.
        self.paginaActualizar.setObjectName("paginaActualizar")
        self.botonAtrasEnActualizar = QPushButton(self.paginaActualizar)
        self.botonAtrasEnActualizar.setObjectName("botonAtrasEnActualizar")
        self.botonAtrasEnActualizar.setGeometry(QRect(0, 0, 41, 41))
        self.botonAtrasEnActualizar.setStyleSheet("QPushButton{border-radius: 5px;}""QPushButton:hover {background-color:  rgb(70, 70, 70);}")
        self.botonAtrasEnActualizar.setToolTip(QCoreApplication.translate("paginaActualizar", "Atras"))
        self.botonAtrasEnActualizar.setIcon(icon8)
        self.botonAtrasEnActualizar.setIconSize(QSize(25, 25))
        self.inputBuscarEnActualizar = QLineEdit(self.paginaActualizar)
        self.inputBuscarEnActualizar.setObjectName("inputBuscarEnActualizar")
        self.inputBuscarEnActualizar.setGeometry(QRect(250, 60, 421, 41))
        self.inputBuscarEnActualizar.setStyleSheet("color: rgb(255, 255, 255); font: 10pt \"Consolas\"; background-color: rgb(85, 85, 85); border-radius: 18px;")
        self.inputBuscarEnActualizar.setPlaceholderText(QCoreApplication.translate("paginaActualizar", "Buscar"))
        self.inputBuscarEnActualizar.setAlignment(Qt.AlignCenter)

        self.tablaActualizar = QTableWidget(self.paginaActualizar) # Tabla Actualizar.
        self.tablaActualizar.setColumnCount(6)
        for encabezado, num in zip(self.encabezadosTabla,range(6)): # poner encabezados a la tabla Actualizar.
            tablWidgetItem1=QTableWidgetItem()
            self.tablaActualizar.setHorizontalHeaderItem(num, tablWidgetItem1)
            tablWidgetItem1.setText(QCoreApplication.translate("paginaActualizar", encabezado))

        self.tablaActualizar.setObjectName("tablaActualizar")
        self.tablaActualizar.setGeometry(QRect(0, 160, 900, 291))
        self.tablaActualizar.setMinimumSize(QSize(900, 0))
        self.tablaActualizar.setMaximumSize(QSize(900, 16777215))
        self.tablaActualizar.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.tablaActualizar.setAlternatingRowColors(True)
        self.tablaActualizar.horizontalHeader().setVisible(True)
        self.tablaActualizar.horizontalHeader().setCascadingSectionResizes(True)
        self.tablaActualizar.horizontalHeader().setProperty("showSortIndicator", False)
        self.tablaActualizar.horizontalHeader().setStretchLastSection(True)
        self.tablaActualizar.verticalHeader().setVisible(False)
        self.tablaActualizar.verticalHeader().setHighlightSections(False)
        self.botonActualizarEnActualizar = QPushButton(self.paginaActualizar)
        self.botonActualizarEnActualizar.setObjectName("botonActualizarEnActualizar")
        self.botonActualizarEnActualizar.setGeometry(QRect(770, 550, 101, 31))
        self.botonActualizarEnActualizar.setStyleSheet("QPushButton{color: rgb(255, 255, 255); font: 10pt \"Consolas\"; background-color: rgb(100, 100, 100); border-radius: 10px;}""QPushButton:hover {background-color:  rgb(63, 133, 149);}")
        self.botonActualizarEnActualizar.setText(QCoreApplication.translate("paginaActualizar", "Actualizar"))
        self.labelConfirmacionActualizado = QLabel(self.paginaActualizar)
        self.labelConfirmacionActualizado.setObjectName("labelConfirmacionActualizado")
        self.labelConfirmacionActualizado.setGeometry(QRect(10, 560, 171, 21))
        self.labelConfirmacionActualizado.setStyleSheet("color: rgb(151, 255, 151); font: 9pt \"Consolas\";")
        self.labelIdEnActualizar = QLabel(self.paginaActualizar)
        self.labelIdEnActualizar.setObjectName("labelIdEnActualizar")
        self.labelIdEnActualizar.setGeometry(QRect(10, 460, 61, 41))
        self.labelIdEnActualizar.setStyleSheet("color: rgb(255, 243, 73);  font: 11pt \"Arial\"; background-color: rgb(85, 85, 85); border-radius: 8px;")
        self.labelIdEnActualizar.setAlignment(Qt.AlignCenter)

        self.inputProductoEnActualizar = QLineEdit(self.paginaActualizar)
        self.inputProductoEnActualizar.setObjectName("inputProductoEnActualizar")
        self.inputProductoEnActualizar.setGeometry(QRect(80, 460, 271, 41))
        self.inputProductoEnActualizar.setStyleSheet("color: rgb(255, 255, 255);  font: 10pt \"Arial\"; background-color: rgb(85, 85, 85); border-radius: 8px;")
        self.inputMarcaEnActualizar = QLineEdit(self.paginaActualizar)
        self.inputMarcaEnActualizar.setObjectName("inputMarcaEnActualizar")
        self.inputMarcaEnActualizar.setGeometry(QRect(360, 460, 231, 41))
        self.inputMarcaEnActualizar.setStyleSheet("color: rgb(255, 255, 255);  font: 10pt \"Arial\"; background-color: rgb(85, 85, 85); border-radius: 8px;")
        self.inputPrecioEnActualizar = QLineEdit(self.paginaActualizar)
        self.inputPrecioEnActualizar.setObjectName("inputPrecioEnActualizar")
        self.inputPrecioEnActualizar.setGeometry(QRect(600, 460, 101, 41))
        self.inputPrecioEnActualizar.setStyleSheet("color: rgb(255, 255, 255);  font: 10pt \"Arial\"; background-color: rgb(85, 85, 85); border-radius: 8px;")
        self.inputStockEnActualizar = QLineEdit(self.paginaActualizar)
        self.inputStockEnActualizar.setObjectName("inputStockEnActualizar")
        self.inputStockEnActualizar.setGeometry(QRect(710, 460, 91, 41))
        self.inputStockEnActualizar.setStyleSheet("color: rgb(255, 255, 255);  font: 10pt \"Arial\"; background-color: rgb(85, 85, 85); border-radius: 8px;")
        self.inputInflacionEnActualizar = QLineEdit(self.paginaActualizar)
        self.inputInflacionEnActualizar.setObjectName("inputInflacionEnActualizar")
        self.inputInflacionEnActualizar.setGeometry(QRect(810, 460, 81, 41))
        self.inputInflacionEnActualizar.setStyleSheet("color: rgb(255, 255, 255);  font: 10pt \"Arial\"; background-color: rgb(85, 85, 85); border-radius: 8px;")
        self.paginas.addWidget(self.paginaActualizar)

        self.paginaEliminar = QWidget() # Pagina Eliminar
        self.paginaEliminar.setObjectName("paginaEliminar")
        self.botonAtrasEnEliminar = QPushButton(self.paginaEliminar)
        self.botonAtrasEnEliminar.setObjectName("botonAtrasEnEliminar")
        self.botonAtrasEnEliminar.setGeometry(QRect(0, 0, 41, 41))
        self.botonAtrasEnEliminar.setStyleSheet("QPushButton{border-radius: 5px;}""QPushButton:hover {background-color:  rgb(70, 70, 70);}")
        self.botonAtrasEnEliminar.setToolTip(QCoreApplication.translate("paginaEliminar", "Atras"))
        self.botonAtrasEnEliminar.setIcon(icon8)
        self.botonAtrasEnEliminar.setIconSize(QSize(25, 25))
        self.inputBuscarEnEliminar = QLineEdit(self.paginaEliminar)
        self.inputBuscarEnEliminar.setObjectName("inputBuscarEnEliminar")
        self.inputBuscarEnEliminar.setGeometry(QRect(250, 60, 431, 41))
        self.inputBuscarEnEliminar.setStyleSheet("color: rgb(255, 255, 255); font: 10pt \"Consolas\"; background-color: rgb(85, 85, 85); border-radius: 18px;")
        self.inputBuscarEnEliminar.setPlaceholderText(QCoreApplication.translate("paginaEliminar", "Buscar"))
        self.inputBuscarEnEliminar.setAlignment(Qt.AlignCenter)

        self.tablaEliminar = QTableWidget(self.paginaEliminar) # Tabla Eliminar.
        self.tablaEliminar.setColumnCount(6)
        for encabezado, num in zip(self.encabezadosTabla,range(6)): # coloca encabezados a la tabla eliminar.
            tablWidgetItem2=QTableWidgetItem()
            self.tablaEliminar.setHorizontalHeaderItem(num, tablWidgetItem2)
            tablWidgetItem2.setText(QCoreApplication.translate("paginaEliminar", encabezado))

        self.tablaEliminar.setObjectName("tablaEliminar")
        self.tablaEliminar.setGeometry(QRect(0, 160, 900, 321))
        self.tablaEliminar.setMinimumSize(QSize(900, 0))
        self.tablaEliminar.setMaximumSize(QSize(900, 16777215))
        self.tablaEliminar.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.tablaEliminar.setAlternatingRowColors(True)
        self.tablaEliminar.horizontalHeader().setCascadingSectionResizes(True)
        self.tablaEliminar.horizontalHeader().setProperty("showSortIndicator", False)
        self.tablaEliminar.horizontalHeader().setStretchLastSection(True)
        self.tablaEliminar.verticalHeader().setVisible(False)
        self.tablaEliminar.verticalHeader().setHighlightSections(False)
        self.botonEliminarEnEliminar = QPushButton(self.paginaEliminar)
        self.botonEliminarEnEliminar.setObjectName("botonEliminarEnEliminar")
        self.botonEliminarEnEliminar.setGeometry(QRect(790, 530, 81, 31))
        self.botonEliminarEnEliminar.setStyleSheet("QPushButton{color: rgb(255, 255, 255); font: 10pt \"Consolas\"; background-color: rgb(100, 100, 100); border-radius: 10px;}""QPushButton:hover {background-color:  rgb(63, 133, 149);}")
        self.botonEliminarEnEliminar.setText(QCoreApplication.translate("paginaEliminar", "Eliminar"))
        self.labelConfirmacionEliminado = QLabel(self.paginaEliminar)
        self.labelConfirmacionEliminado.setObjectName("labelConfirmacionEliminado")
        self.labelConfirmacionEliminado.setGeometry(QRect(10, 540, 201, 21))
        self.labelConfirmacionEliminado.setStyleSheet("color: rgb(151, 255, 151); font: 9pt \"Consolas\";")
        self.paginas.addWidget(self.paginaEliminar)

        self.paginaAjustes = QWidget() # Pagina Ajustes (sin funcionalidad).
        self.paginaAjustes.setObjectName("paginaAjustes")
        self.botonAtrasEnAjustes = QPushButton(self.paginaAjustes)
        self.botonAtrasEnAjustes.setObjectName("botonAtrasEnAjustes")
        self.botonAtrasEnAjustes.setGeometry(QRect(0, 0, 41, 41))
        self.botonAtrasEnAjustes.setStyleSheet("QPushButton{border-radius: 5px;}""QPushButton:hover {background-color:  rgb(70, 70, 70);}")
        self.botonAtrasEnAjustes.setToolTip(QCoreApplication.translate("paginaAjustes", "Atras"))
        self.botonAtrasEnAjustes.setIcon(icon8)
        self.botonAtrasEnAjustes.setIconSize(QSize(25, 25))
        self.label = QLabel(self.paginaAjustes)
        self.label.setObjectName("label")
        self.label.setGeometry(QRect(250, 210, 471, 151))
        self.label.setStyleSheet("color: rgb(252, 255, 98); font: italic 16pt \"Arial\";")
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setText(QCoreApplication.translate("paginaAjustes", "Funcionalidad No disponible!"))
        self.paginas.addWidget(self.paginaAjustes)

        self.paginaInfo = QWidget() # Pagina Info.
        self.paginaInfo.setObjectName("paginaInfo")
        self.labelInfoEnInfo = QLabel(self.paginaInfo)
        self.labelInfoEnInfo.setObjectName("labelInfoEnInfo")
        self.labelInfoEnInfo.setGeometry(QRect(0, 0, 900, 600))
        self.labelInfoEnInfo.setMinimumSize(QSize(900, 600))
        self.labelInfoEnInfo.setStyleSheet("color: rgb(227, 227, 46); font: italic 12pt \"Arial\";")
        self.labelInfoEnInfo.setAlignment(Qt.AlignCenter)

        self.botonAtrasEnInfo = QPushButton(self.paginaInfo)
        self.botonAtrasEnInfo.setObjectName("botonAtrasEnInfo")
        self.botonAtrasEnInfo.setGeometry(QRect(0, 0, 41, 41))
        self.botonAtrasEnInfo.setStyleSheet("QPushButton{border-radius: 5px;}""QPushButton:hover {background-color:  rgb(70, 70, 70);}")
        self.botonAtrasEnInfo.setToolTip(QCoreApplication.translate("paginaInfo", "Atras"))
        self.botonAtrasEnInfo.setIcon(icon8)
        self.botonAtrasEnInfo.setIconSize(QSize(25, 25))

        self.paginas.addWidget(self.paginaInfo)
        self.layoutDelFramePrincipal.addWidget(self.paginas)
        self.layoutMain.addWidget(self.framePrincipal)
        MainKiosko.setCentralWidget(self.centralwidget)

        self.labelInfoEnInfo.setText(QCoreApplication.translate("paginaInfo", "PROYECTO FINAL PROGRAMACION 1 iTec RIO CUARTO.\n""\n"
"Este proyecto consiste en un gestor de stock para un Kiosko. \n"
"El mismo utiliza una base de datos con una tabla y \n"
"realiza operaciones basicas sobre el stock.\n""\n"
"Los Participantes de este proyecto son: \n"
"* Bulfon, Julieta\n"
"* Gonzalez, Hector\n"
"* Gonzalez Malvestiti, David\n"
"* Guzman, Milton\n"
"* Palacios, Lautaro"))


if __name__ == "__main__":
    app = QApplication(sys.argv) #crear una nueva instancia de QApplication
    windows = UiMainKiosko() #cree una nueva instancia de la interfaz de usuario.
    qMw = QMainWindow() #crear una instancia de QMainWindow
    windows.setupUi(qMw) #cree sus widgets dentro de la ventana que acaba de crear.
    qMw.show() #mostrar la ventana.
    sys.exit(app.exec_()) #Salga del programa cuando cierre la ventana de la aplicación.